#注册中心配置
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:9000/eureka/ #注册中心地址
    register-with-eureka: true #是否注册到注册中心
    fetch-registry: true  #是否从注册中心获取服务
    registry-fetch-interval-seconds: 30
    should-unregister-on-shutdown: true #客户端能否从注册中心下线

  instance:
    prefer-ip-address: true #优先使用ip注册服务
    lease-expiration-duration-in-seconds: 15 #多长时间内如果没有向注册中心发送心跳证明服务下线，一般为服务刷新时间的3倍
    lease-renewal-interval-in-seconds: 5 #向注册中心发送心跳证明自己还活着，默认30s
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: paulo
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
